services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    stdin_open: true
    command: python -m backend.main --host 0.0.0.0 --port 8000 --reset
    env_file:
      - .env
    environment:
      - ENVIRONMENT=local
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - kipp-network

  db:
    image: pgvector/pgvector:pg17
    container_name: db
    restart: always
    user: "${UID}:${GID}"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.db/pgdata:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d django_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - kipp-network

networks:
  kipp-network:
    name: kipp-network

volumes:
  postgres-data:
  postgres-test-data:
  redis-data:
